### ISSUE TITLE
Buggy GeoCoder Results

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#20]
| Issue | Description | URL | Status |
| :-------------: | ------------- | ----- | :-------------: |
| **FIXED** "Portland" suffix | add "Portland" to the search term, and the desired match goes from 1 to 6 in the list | https://ws-st.trimet.org/pelias/v1/search?text=4004%20SW%20BHH <br/>vs:<br/> https://ws-st.trimet.org/pelias/v1/search?text=4004%20SW%20BHH,%20Portland  | FIXED |
| **FIXED**  "Portland" suffix | here, adding "Portland" sees the proper result gone entirely from the list | https://ws-st.trimet.org/pelias/v1/search?text=4004%20SW%20Beaverton-Hillsdale <br/>vs:<br/> https://ws-st.trimet.org/pelias/v1/search?text=4004%20SW%20Beaverton-Hillsdale,%20Portland  | FIXED |
| Wrong City _search_ is broken; _autocomplete_ works | using the wrong city in the _search_ service results in the city record ... very strange | https://ws-st.trimet.org/pelias/v1/search?text=834%20SE%20Lambert%20St,%20Tigard <br/>vs:<br/> https://ws-st.trimet.org/pelias/v1/search?text=834%20SE%20Lambert%20St,%20Portland  <br/>vs:<br/> https://ws-st.trimet.org/pelias/v1/autocomplete?text=834%20SE%20Lambert%20St,%20Tigard  | new |
| Street Abbrev. and Intersections | - "filbert st & 32nd ave" returns the incorrect location, - "filbert  & 32nd ave" returns nothing, - only "filbert  & 32nd" works | https://ws-st.trimet.org/pelias/v1/autocomplete?text=filbert%20st%20%26%2032nd%20ave <br/>vs:<br/> https://ws-st.trimet.org/pelias/v1/autocomplete?text=filbert%20%26%2032nd%20ave <br/>vs:<br/> https://ws-st.trimet.org/pelias/v1/autocomplete?text=filbert%20%26%2032nd | new |

**Comment by ttlin1** [comment]
Here's another issue:

Issue | Description | URL | Status
-- | -- | -- | --
Street Abbrev. | "filbert st & 32nd ave" returns the incorrect location, but "filbert  & 32nd ave" does not | https://ws-st.trimet.org/pelias/v1/autocomplete?text=filbert%20st%20%26%2032nd%20ave vs: https://ws-st.trimet.org/pelias/v1/autocomplete?text=filbert%20%20%26%2032nd%20ave | new

**Comment by orangejulius** [comment]
I was able to take a look at these briefly. 

Case 1 and 2: looks like `libpostal` is doing the wrong thing. A query for [4004 SW Beaverton-Hillsdale hwy, Portland](https://ws-st.trimet.org/pelias/v1/search?text=4004%20SW%20Beaverton-Hillsdale%20hwy,%20Portland) does the right thing in both cases. We already have lots of logic for working around incorrect libpostal queries, and there may also be updates to libpostal that help with this. We'll report back with an update.

Case 3: both our ongoing work with `postal cities` (https://github.com/pelias/pelias/issues/396) as well as some improvements we made specifically to support "nearby, but not quite correct" city matches can help here (https://github.com/pelias/placeholder/pull/117)

Case 4: I have opened https://github.com/pelias/pelias/issues/740 which tracks this issue. We've known about it for a while and _should_ be able to solve it. Update: because it involves intersections, it may not be a small fix

**Comment by missinglink** [comment]
The `libpostal` parses are particularly bad for street names where the suffix has been omitted, as in the example:

```
4004 SW Beaverton-Hillsdale, Portland

      "parsed_text": {
        "number": "4004",
        "street": "sw",
        "neighbourhood": "beaverton-hillsdale",
        "city": "portland"
      }
```

If the street suffix (in this case `HWY` or `Highway`) is provded then `libpostal` seems to recognize that it's a street.

```
4004 SW Beaverton-Hillsdale HWY, Portland

      "parsed_text": {
        "number": "4004",
        "street": "sw beaverton-hillsdale hwy",
        "city": "portland"
      }
```

I think that's the root of this specific issue?

I think that omitting both the street suffix and the locality resulting in a correct parse is just pure luck, [libpostal is not designed to be used without any locality information present in the text](https://github.com/openvenues/libpostal/issues/344#issuecomment-395986223), we may be seeing a fallback behaviour.

```
4004 SW Beaverton-Hillsdale

      "parsed_text": {
        "number": "4004",
        "street": "sw beaverton-hillsdale"
      }
```

**Comment by missinglink** [comment]
Regarding the postal locality issue `Wrong City (no #3)`, I am pretty confident this will be resolved by the "Postal Cities" work which I am close to completing.

The tl;dr is that this address is asscoiated with the ZIP of `97202`, the new "Postal Cities" code will check all of openstreetmap to get the concensus of which locality the local residents associate with `97202` within the USA.

If the majority of places on OSM for `97202` are `Tigard`, then `Tigard` will be used for labelling and both `Tigard` and `Portland` will be available for matching using search.

I hope to finish this work within the next two weeks, the 'work' here is to preprocess all of openstreetmap in order to make the whole "check all of OSM" problem an `O(1)` problem, and to write scripts which allow us to recreate that file at will.

**Comment by missinglink** [comment]
The intersections issue is complex, I'd say that will not be a quick fix.

We will need to consider changes to the parsing logic as well as the matching logic in order to accomodate queries like this.

**Comment by missinglink** [comment]
@fpurcell looks like the first two issues are now resolved and the fix is live on your servers via https://github.com/pelias/api/pull/1197

**Comment by fpurcell** [comment]
I agree @missinglink  ... first 2 issues are fixed (and marked as such above).  Definitely see what you mean about parsing (e.g., I've seen "NE"  being parsed as State by addressit with certain intersection formatted queries  :-).  

One other interesting thing: I changed up our intersection generation to remove duplicates (e.g., there's only a "SE 32nd Ave & SE Filbert St" record ... whereas in the past there'd also be a "SE Filbert St & SE 32nd Ave" _duplicate_ ).  As a result, having any street type or prefix in the intersection query now fails ... so both https://ws-st.trimet.org/pelias/v1/autocomplete?text=Filbert%20St%20%26%2032nd%20Ave  -or-  https://ws-st.trimet.org/pelias/v1/autocomplete?text=SE%20Filbert%20St%20%26%20SE%2032nd%20Ave are gumming up the works.  That said, the most common intersection query https://ws-st.trimet.org/pelias/v1/autocomplete?text=Filbert%20%26%2032nd is working great, so we're partway there...

**Comment by fpurcell** [comment]
Most (maybe all) of these issues are now fixed with the new address parser.  Closing...
