### ISSUE TITLE
Intersection Work - Summer 2019

### ISSUE THREAD

**Issue by fpurcell** [OpenTransitTools-BonePile/trimet-mod-pelias#32]
- "SE 9th Ave & SE Lambert"  works nicely, but "SE 9th Ave and SE Lambert" has many ambiguous hits. 
  NOTE: 
  parsed_text: {
    admin: "Lambert",
    street: "Ave and SE",
    locality: "Lambert",
    subject: "Ave and SE"
  },
- xxx

NOTE: older #24 and #25

**Comment by missinglink** [comment]
I'm getting a different result to what you posted on our test server, so I suspect that the configurations are different?
I'm also seeing a different parse (which is also not correct but results in only one result):

```
http://54.146.200.62/v1/autocomplete?text=SE%209th%20Ave%20%26%20SE%20Lambert

"text": "SE 9th Ave & SE Lambert",
"parser": "pelias",
"parsed_text": {
"subject": "SE 9th Ave",
"street": "SE 9th Ave",
"locality": "Lambert",
"admin": "& SE Lambert"
},

1) SE Lambert St & SE 9th Ave, Portland, OR, USA
```

My guess is, since the parses are different, you might be running an older version of the docker images?

It's really difficult to correctly parse streets without the 'generic' part (ie. SE Lambert STREET) in this query, although as you can see in my example, I have tried to account for that and the queries should still return the correct result despite an inaccurate parse.

**Comment by missinglink** [comment]
I just checked the config on that dev server and it's running the `pelias_parser` branch on https://github.com/geocodeearth/trimet-docker without any modifications

**Comment by missinglink** [comment]
So I'd suggest checking the versions first, which could be an easy fix.
If that doesn't work then it would be helpful if I could send requests to your server to debug the problem further.

**Comment by fpurcell** [comment]
9th & Lamb looking good now...
